before:
  hooks:
    - go mod download
builds:
  - main: main.go
    binary: sops-operator
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
    ldflags:
      - >-
        -X github.com/riskalyze/sops-operator/pkg/version.Version={{ .Tag }}
        -X github.com/riskalyze/sops-operator/pkg/version.GitCommit={{ .Commit }}
        -X github.com/riskalyze/sops-operator/pkg/version.BuildDate={{ .Date }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
archives:
  - files:
      - LICENSE
      - README.md
kos:
  - repository: docker.io/riskalyze/sops-operator
    tags:
    - '{{.Tag}}'
    - latest
    bare: true
    working_dir: build
    preserve_import_paths: false
    platforms:
    - linux/amd64
    - linux/arm64
