
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - craftypath.github.io
  resources:
  - sopssecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - craftypath.github.io
  resources:
  - sopssecrets/status
  verbs:
  - get
  - patch
  - update
