kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sops-operator
subjects:
  - kind: ServiceAccount
    name: sops-operator
roleRef:
  kind: ClusterRole
  name: sops-operator
  apiGroup: rbac.authorization.k8s.io
