apiVersion: apps/v1
kind: Deployment
metadata:
  name: sops-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sops-operator
  template:
    metadata:
      labels:
        name: sops-operator
    spec:
      serviceAccountName: sops-operator
      containers:
        - name: sops-operator
          image: craftypath/sops-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sops-operator"
